# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IssueAgent < Formula
  desc ""
  homepage ""
  version "0.20.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clover0/issue-agent/releases/download/v0.20.0/issue-agent_darwin_amd64.tar.gz"
      sha256 "31c9efe1dd87c9cd8a9903dcef06634dc41b87247e00c6ef2ec8b62c197c38d3"

      def install
        bin.install "issue-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clover0/issue-agent/releases/download/v0.20.0/issue-agent_darwin_arm64.tar.gz"
      sha256 "17cfab0071c323fe507aa28db1b58915d7a170c649b883f75feeeb0ed9c54e27"

      def install
        bin.install "issue-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/clover0/issue-agent/releases/download/v0.20.0/issue-agent_linux_amd64.tar.gz"
      sha256 "9a17dc82c5129faa8a104b85b7fade41dc047fa1a2bc38f4756a0d7e76e58784"
      def install
        bin.install "issue-agent"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/clover0/issue-agent/releases/download/v0.20.0/issue-agent_linux_arm64.tar.gz"
      sha256 "447e320c1875e94bb5f2a9d26aafec2ecebe862ed69db6dc8579106c132994b4"
      def install
        bin.install "issue-agent"
      end
    end
  end

  test do
    system "#{bin}/issue-agent version"
  end
end
