# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IssueAgent < Formula
  desc ""
  homepage ""
  version "0.10.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clover0/issue-agent/releases/download/v0.10.1/issue-agent_darwin_amd64.tar.gz"
      sha256 "dd20d458a5532997af1be422a607661fce4877699bd4f3111d78524055e9349f"

      def install
        bin.install "issue-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clover0/issue-agent/releases/download/v0.10.1/issue-agent_darwin_arm64.tar.gz"
      sha256 "f71ce92841c6c102d14cf9399d395d40fbffcc762b530ab2acab31243474f4e5"

      def install
        bin.install "issue-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clover0/issue-agent/releases/download/v0.10.1/issue-agent_linux_amd64.tar.gz"
        sha256 "fd6593f41a746d07c94d5adec56e8224f8b2f9d287c2fad25c0eb446b271689c"

        def install
          bin.install "issue-agent"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clover0/issue-agent/releases/download/v0.10.1/issue-agent_linux_arm64.tar.gz"
        sha256 "6449eb95062f129edf245e74a11d4abffd3abf02fe64beceb9f89eac5dcaf68e"

        def install
          bin.install "issue-agent"
        end
      end
    end
  end

  test do
    system "#{bin}/issue-agent version"
  end
end
